### ISSUE TITLE
hyh - UToken amount to be burned on redeem can be less than the corresponding amount withdrawn

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-union-finance-update-2-judging#122]
hyh

Medium

# UToken amount to be burned on redeem can be less than the corresponding amount withdrawn

## Summary

The amount of the UToken to be burned on redeem is rounded down. This happens after actual withdrawal and allows redeeming user to receive extra funds. This can be run multiple times in L2 environment, accumulating material profit whenever the associated gas costs are lower than the corresponding rounding in favor of the caller.

## Vulnerability Detail

When `exchangeRate` figure accumulates enough value to imply a significant rounding, it can be exploited via having less UTokens burnt than underlying tokens received. While the most important zero UToken amount case is correctly controlled for, the partial loss of precision case is not, enabling the surface of attacker supplying a significant number of the smallest possible dust redeem calls each receiving slightly more value than was burned.

## Impact

Attacker can drain value directly from the UToken when `exchangeRate` is big enough, while gas costs are low enough to have the rounding effect exceeding the cumulative costs even slightly. When this happens it can be possible to drain a significant share of the holdings as there is no direct limitation on the number of calls, i.e. the enabling conditions do not change after each of them.

## Code Snippet

There are no minimum redeem amount:

[UToken.sol#L845-L859](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L845-L859)

```solidity
    function redeem(uint256 amountIn, uint256 amountOut) external override whenNotPaused nonReentrant {
        if (!accrueInterest()) revert AccrueInterestFailed();
        if (amountIn != 0 && amountOut != 0) revert AmountError();
        if (amountIn == 0 && amountOut == 0) revert AmountZero();

        uint256 exchangeRate = _exchangeRateStored();

        // Amount of the underlying token to redeem
        uint256 underlyingAmount = amountOut;

        if (amountIn > 0) {
            // We calculate the exchange rate and the amount of underlying to be redeemed:
            // underlyingAmount = amountIn x _exchangeRateStored
            underlyingAmount = decimalReducing((amountIn * exchangeRate) / WAD, underlyingDecimal);
        }
```

And amount to burn from the redeeming user is scaled down:

[UToken.sol#L867-L872](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L867-L872)

```solidity
        uint256 actualAmount = decimalScaling(underlyingAmount - remaining, underlyingDecimal);
>>      uint256 realUtokenAmount = (actualAmount * WAD) / exchangeRate;
        if (realUtokenAmount == 0) revert AmountZero();
        _burn(msg.sender, realUtokenAmount);

        _totalRedeemable -= actualAmount;
```

While zero burn case is controlled for, the dust burn cases (having exchange rate of `2`, ask for and receive `3.9` units of underlying, burn `3.9 / 2 = 1` UTokens) are still possible.

## Tool used

Manual Review

## Recommendation

Consider scaling up the UToken amount needed, e.g.:

[UToken.sol#L867-L872](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L867-L872)

```diff
        uint256 actualAmount = decimalScaling(underlyingAmount - remaining, underlyingDecimal);
-       uint256 realUtokenAmount = (actualAmount * WAD) / exchangeRate;
+       uint256 realUtokenAmount = (actualAmount * WAD + exchangeRate - 1) / exchangeRate;
        if (realUtokenAmount == 0) revert AmountZero();
        _burn(msg.sender, realUtokenAmount);

        _totalRedeemable -= actualAmount;
```

**Comment by dmitriia** [comment]
> Low QA on rounding direction

There is no such rule in Sherlock [judging rules](https://docs.sherlock.xyz/audits/judging/judging). Direction of rounding can represent valid medium given the circumstances, e.g. [Napier-101](https://github.com/sherlock-audit/2024-01-napier-judging/issues/101), [Tapioca-39](https://github.com/sherlock-audit/2024-02-tapioca-judging/issues/39).

**Comment by dmitriia** [comment]
Escalate
When `exchangeRate` figure accumulates enough value and costs are low enough is can be possible to profitable execute the surface. Even a tiny profit can be exaggerated by repeating it many times over in a short period of time as both `exchangeRate` and gas conditions won't change. This way it's a high impact and low probability, i.e. medium severity issue.

**Comment by sherlock-admin3** [comment]
> Escalate
> When `exchangeRate` figure accumulates enough value and costs are low enough is can be possible to profitable execute the surface. Even a tiny profit can be exaggerated by repeating it many times over in a short period of time as both `exchangeRate` and gas conditions won't change. This way it's a high impact and low probability, i.e. medium severity issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
`actualAmount` is already `WAD` (1e18) scaled. With the default truncation of 1 wei difference on each burn, I don't think this dust impact deserve a medium severity.

**Comment by crypt0nX** [comment]
> `actualAmount` is already `WAD` (1e18) scaled. With the default truncation of 1 wei difference on each burn, I don't think this dust impact deserve a medium severity.  

Hi here is another aspect of the issue, https://github.com/sherlock-audit/2024-06-union-finance-update-2-judging/issues/28 I believe in this case any token whose decimals is small can cause problem too.

**Comment by dmitriia** [comment]
> `actualAmount` is already `WAD` (1e18) scaled. With the default truncation of 1 wei difference

There is no default here, the truncation depends on the numerical values. Say if `underlyingAmount - remaining = 39`, `actualAmount = 39e12`, `exchangeRate = 2e31`, then `realUtokenAmount = 39*1e12*1e18/2e31 = floor(1.95) = 1`. So, if `0.95` of UToken is more valuable than gas costs (in L2 environment, where Union is deployed too), which can be the case when index is big enough, as in this example, then it is profitable to run this quite large number of times, draining the protocol. So it is very high (critical) impact and very low probability issue, which gives medium severity.

**Comment by maxweng** [comment]
@dmitriia We scale all amounts up to 18 decimals before the internal calculations. So it's fine to deal with small amounts like 1 dai, or even 0.0001 dai etc. The issue only happens when the amount is 1 order larger than the exchange rate (not in 18 decimals). For example, if the exchange rate is 10 or less, only dai 10 wei or less will be truncated and so on. 
You can also check out the test I created [here](https://github.com/unioncredit/union-v2-contracts/blob/caa08cdbc78fe4d3fa1e3f1a56db5751e28ef7cf/test/audit-2024/uni-1994-utoken-amount-to-be-burned-on-redeem-can-be-less-than-the.ts) if that makes it better understood.

**Comment by dmitriia** [comment]
@maxweng Yes, that's true, very large exchange rate is the prerequisite here. It's better to close the vector completely though.

**Comment by WangSecurity** [comment]
This report is about the precision loss and it falls under the following rule:
> PoC is required for all issues falling into any of the following groups:
issues related to precision loss

I believe this report lacks POC (coded or written) and sufficient proof rounding down precision loss. I see the following example, but I don't see it as sufficient proof:

> While zero burn case is controlled for, the dust burn cases (having exchange rate of 2, ask for and receive 3.9 units of underlying, burn 3.9 / 2 = 1 UTokens) are still possible

Hence, the decision is that this report has to remain invalid. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [dmitriia](https://github.com/sherlock-audit/2024-06-union-finance-update-2-judging/issues/122/#issuecomment-2241181068): rejected

**Comment by WangSecurity** [comment]
After further considering the POC rule, the decision is that submitting it after the contest when the lead judge requests it or during the escalations is sufficient. Excuse me for the confusion previously. I believe this [comment] shows the precision loss and loss of funds.

Hence, I’m planning to override the decision and validate this issue with medium severity. @dmitriia @mystery0x are there any duplicates?

**Comment by MD-YashShah1923** [comment]
@WangSecurity This should not be considered valid medium issue.
Reasons :
- First of all to prevent precision loss , the function was scaled up by 1e18 value as commented by @maxweng (sponsor). So to prevent this issue protocol team already took steps by scaling the numerator by 1e18
- Secondly the exchangeRate considered in the above  example is `exchangeRate = 2e31` which is impossible. This much of exchangeRate() (20,000,000,000,000 * 1e18) can never be increased if we think practically.
- This precision loss is still not possible when actualAmount is a multiple of exchangeRate due to precision loss would be zero leading zero profit for attacker.
- Even Watson suggested to close this issue in above comment " It's better to close the vector completely though."
- Mitigation provided by watson is also incorrect.
-  This issue should not even be considered as low given the above points given by me and also comment given by @maxweng.

Correct me if i am wrong here.

@WangSecurity Hope you take steps accordingly and reverse your decision.

**Comment by WangSecurity** [comment]
Yep, I see the pre-requisites are either high exchange rate and low amount to redeem. And to clarify, in order to lose at least 1 dai, i.e. 1e18, the exchange rate has to be >1e36, correct? @MD-YashShah1923 @dmitriia

**Comment by MD-YashShah1923** [comment]
- According to me loss is less than 1 dai.
- But for this loss to happen which is less than 1 dai , the exchange rate should be (20,000,000,000,000,000 * 1e18) which is impossible to achieve and never will be achieved in future as well.
- And there would be no loss  when actualAmount is a multiple of exchangeRate due to precision loss would be zero at that moment. And even when actualAmount is less  than exchangeRate at that time the transaction would revert due to the given condition  `if (realUtokenAmount == 0) revert AmountZero();` and there would be no loss.
- The Watson is assuming the exchangeRate to a very very high value (20,000,000,000,000,000 * 1e18) which is even not possible to happen so this issue should be invalidated here itself given the assumption of this much high exchangeRate.

Correct me if i am wrong here.

- Thanks @WangSecurity sir for quick reply

**Comment by WangSecurity** [comment]
Yep, I see, even if the exchange rate is not that high, e.g. 1e23 which is still relatively high, the amount to be redeemed should be <1e5 to round down to zero which is quite small.

Hence, admit it was a mistake on my end and this issue to cause losses exceeding small and finite amounts requires an exchange rate be higher than the price of any crypto asset currently. Thus, I agree it should be low severity.

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/unioncredit/union-v2-contracts/pull/174

**Comment by dmitriia** [comment]
> The protocol team fixed this issue in the following PRs/commits: [unioncredit/union-v2-contracts#174](https://github.com/unioncredit/union-v2-contracts/pull/174)

Fix looks ok
