### ISSUE TITLE
Bauchibred - Anyone can sidestep the whitelisting protection for token transfers

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-union-finance-update-2-judging#18]
Bauchibred

Medium

# Anyone can sidestep the whitelisting protection for token transfers

## Summary

See _title_.

## Vulnerability Detail

Take a look at https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/OpUNION.sol#L25-L31

```solidity
    function _beforeTokenTransfer(address from, address to, uint256 amount) internal override {
        super._beforeTokenTransfer(from, to, amount);

        if (whitelistEnabled) {
            require(isWhitelisted(msg.sender) || to == address(0), "Whitelistable: address not whitelisted");
        }
    }
```

This is the overriden ERC20 hook that is called before any transfer of tokens.

The overriden implementation now includes a check to see if the sender is whitelisted before allowing the transfer, when `whitelistEnabled`.

Issue however is that this is wrongly done, this is because the the whitelisted check is done against the `msg.sender` and not the `from` where the tokens are being sent from.

This then allows someone that got unwhitelisted to just approve a whitelisted account their tokens and they can side step this check, since the `isWhitelisted()` check would no longer fail.

## Impact

Core functionality is broken because anyone can now sidestep the whitelisting protection for token transfers.

Would be key to note that it's been clearly [documented](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/Whitelistable.sol#L26-L27) that whenever the whitelist is enabled then transfers are only to be allowed from whitelisted accounts, which would not be the case as shown in this report anyone can sidestep the restriction.

## Code Snippet

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/OpUNION.sol#L25-L32.

## Tool used

Manual Review

## Recommendation

Consider applyting these changes https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/OpUNION.sol#L25-L32

```diff
    function _beforeTokenTransfer(address from, address to, uint256 amount) internal override {
        super._beforeTokenTransfer(from, to, amount);

        if (whitelistEnabled) {
-            require(isWhitelisted(msg.sender) || to == address(0), "Whitelistable: address not whitelisted");
+            require(isWhitelisted(from) || to == address(0), "Whitelistable: address not whitelisted");
        }
    }

```

**Comment by Bauchibred** [comment]
This should be rejudged, can't seem to find the judge's reasoning for invalidating the report, and I believe the report to be valid.

**Comment by bG9zZXIvZmFpbHVyZQ** [comment]
Escalate 

On behalf of @Bauchibred

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> On behalf of @Bauchibred
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
Reasonings are yet to be provided by the sponsors disputing this finding.

**Comment by WangSecurity** [comment]
@Bauchibred I agree that this check looks incorrect, but before giving any decision, do we have information (in docs or code comments) on what the correct check should be and can't it be a design decision?

**Comment by Bauchibred** [comment]
> @Bauchibred I agree that this check looks incorrect, but before giving any decision, do we have information (in docs or code comments) on what the correct check should be and can't it be a design decision?

Afaik, the only information in the code comment/docs provided is [this](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/Whitelistable.sol#L26-L27), which indicates that if the whitelisting is enabled then transfers should only be accepted from whitelisted addresses, which should directly translate to needing the check to be done on the account whose tokens is being transferred [via the check in `_beforeTokenTransfer()`](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/OpUNION.sol#L29) to ensure the whitelisting functionality is correctly implemented.

**Comment by WangSecurity** [comment]
Hey @Bauchibred! I've checked with the protocol team and it's indeed their intention to check only the `msg.sender` and not the "from/to" addresses.

Hence, I'm planning to reject this escalation since the check for whitelisted addresses functions as it should and leave the issue as it is.

**Comment by Bauchibred** [comment]
> Hey @Bauchibred! I've checked with the protocol team and it's indeed their intention to check only the `msg.sender` and not the "from/to" addresses.



Hi, this should count as information brought after the contest has ended and per the rules should not be valid grounds in regards to finalizing the report's validity. As you've hinted earlier the check is wrong per the available docs/code comments during the contest. Using Sherlock's rules, code comments/readMe should be the source of truth so I don't see how we can finalize this as invalid, otherwise sponsors can just come after a contest has ended and say 'XY' is not intended after indicating it's intended in the code comments/readMe during the contest.

**Comment by WangSecurity** [comment]
> Hi, this should count as information brought after the contest has ended and per the rules should not be valid grounds in regards to finalizing the report's validity

Fair point, but that’s not an information about known issues or anything that overrides the rules. This is information about how the protocol intends and should function. Additionally, this question could be asked by any Watson during the contest.

> As you've hinted earlier the check is wrong per the available docs/code comments during the contest.

I didn’t say it’s wrong per the available docs or code comments, I’ve said that it looks incorrect and asked whether there’s information about it.

And as I understand the information I brought doesn’t override the code comments you’ve linked, but explains that code comment.

Therefore, the check for msg.sender being whitelisted as intended and the protocol functions as it should.

The decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by Bauchibred** [comment]
Thanks for replying @WangSecurity but I believe my earlier comment still stands.

To reiterate, this is what's documented:

> Enable whitelist and only allow transfers from whitelisted addresses.

Here's the stance you relayed that the sponsors have after the contest has ended:

> I've checked with the protocol team and it's indeed their intention to check only the msg.sender and not the "from/to" addresses.

These two stances can't be considered outrightly the same, nor can the latter be a clear cut explanation of the former, because the `from` and `msg.sender` addresses are not always the same in the context of [where the check is applied](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/OpUNION.sol#L29). So, which information should we use? One that was available during the contest or the one added after the contest has finalized? 

I mean sponsors can come to the conclusion to tag this as "won't fix" for whatever reason, but I don't see a valid argument as to how this report should be rejected per the information available during the contest.

**Comment by WangSecurity** [comment]
I agree with you that the comment is not clear. On the one hand, it can mean to check the `from` address. On the other hand, it can mean to check the address that initiates the transaction. 

Anyway, the rule about code comments applies and the best way is of course to verify during the contest if the specific comment is up-to-date and correct and what the protocol's intention is.

About the information that I've asked the sponsor about, the information is how the protocol intends to work, not something that overrides the rules. And as we can see the protocol does exactly what it intends here, so the issue is incorrect factually and the check is implemented correctly. In that case, I cannot validate and reward that report, unfortunately. Again, the intention of the protocol, i.e. how the protocol should function can always be clarified during the time of the contest. I don't have this ability since I don't have time to check each codebase whilst dealing with other escalations. Therefore, I ask about the intention and how the protocol is designed post-contest. Again, if it was indeed an issue, not the design and the protocol said it's a known one, but didn't include it in the README, I would validate it. But, it's the design and the code works correctly here. 

Hence, the decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by Bauchibred** [comment]
>... so the issue is incorrect factually

Imho this is entirely baseless, using "facts", this report is correct, cause even if the "intention" of the protocol is to have the check on the "msg.sender" as you claim they've hinted, the report is still valid since anyone that's unwhitelisted can still sidestep the protection.

There are _thousands_ of ways we can possibly _translate_ what has been [documented here](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/Whitelistable.sol#L26-L27) to say [this check](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/OpUNION.sol#L29) is coded as "intended". However, there is only one important question for this report: Can unwhitelisted accounts still process transfers even after the whitelisting protection has been enabled? The answer to that is "yes". To finalize, you are Sherlock's HoJ, so your word is rule. While I disagree with your decision, we can't keep going in circles. I have to respect your decision, so thanks for your time!

**Comment by WangSecurity** [comment]
> Imho this is entirely baseless, using "facts", this report is correct, cause even if the "intention" of the protocol is to have the check on the "msg.sender" as you claim they've hinted, the report is still valid since anyone that's unwhitelisted can still sidestep the protection

The intended protection is still to verify the address who initiates the transfer, be that from, to or a third party address. Still, the intention is to verify the msg.sender and not any other address involved in the transaction. Therefore, I don’t think we can say it’s sidestepping the whitelist protection because it’s the design to verify the addresses in that way.

> There are thousands of ways we can possibly translate what has been [documented here](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/Whitelistable.sol#L26-L27) to say [this check](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/OpUNION.sol#L29) is coded as "intended". However, there is only one important question for this report: Can unwhitelisted accounts still process transfers even after the whitelisting protection has been enabled? The answer to that is "yes".

I believe the same as above applies, this is the design of the whitelist mechanic of Union. Therefore, it’s not sidestepping the protection, because it’s the specific design. Additionally, even if from or to addresses are not whitelisted, they still need a whitelisted 3rd party address to make the transfer.

Hence, the decision remains the same, reject the escalation and leave the issue as it is.

**Comment by Bauchibred** [comment]
As I said earlier: 

> There are _thousands_ of ways we can possibly _translate_ what has been [documented here](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/Whitelistable.sol#L26-L27) to say [this check](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/7ffe43f68a1b8e8de1dfd9de5a4d89c90fd6f710/union-v2-contracts/contracts/token/OpUNION.sol#L29) is coded as "intended". However, there is only one important question for this report: Can unwhitelisted accounts still process transfers even after the whitelisting protection has been enabled? The answer to that is "yes". To finalize, you are Sherlock's HoJ, so your word is rule. While I disagree with your decision, we can't keep going in circles. I have to respect your decision, so thanks for your time!

**Comment by WangSecurity** [comment]
I believe I reflected on this part earlier, so if there is no new information or questions, the decision remains the same, reject the escalation leaving the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [bG9zZXivZmFpbHVyZQ](https://github.com/sherlock-audit/2024-06-union-finance-update-2-judging/issues/18/#issuecomment-2241266478): rejected
