### ISSUE TITLE
crypt0n - The division overflow in `ScaledDecimalBase.sol` may cause user losing their funds

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-union-finance-update-2-judging#28]
crypt0n

High

# The division overflow in `ScaledDecimalBase.sol` may cause user losing their funds

### Summary

The division overflow in `ScaledDecimalBase.sol`::`decimalReducing()` may cause user losing their funds, because when user deposit token with small decimal such as USDC, the actual amount return may be 0

### Root Cause

In `ScaledDecimalBase.sol:19` there is a `decimalReducing()` function, the problem is if alice deposit 1000USDC, the `actualAmount` will be 1000*10^6, the decimal is 6, because 6 < 18, the actual amount return by the function is 1000*10^6 / 10 ** 12, because 1000*10^6 < 10 ** 12, so the result will be 0 thanks to solidity rounding feature.In fact, any amount less then 1000000USDC will become 0. 

### Internal pre-conditions

1.if the function ever deal with the scenario I mentioned before, there could be a problem.  

### External pre-conditions

1.Since the function is widely used, any action user have done related to the function will be affected

### Attack Path

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/ScaledDecimalBase.sol#L19

### Mitigation

should check if the return value is zero and make sure the decimal won't too large or too small.

**Comment by crypt0nX** [comment]
Hi there, thanks for the judging @mystery0x ,I believe the issue is valid.In `Utoken`::`redeem`, the `underlyingAmount` is calculated as  `underlyingAmount = decimalReducing((amountIn * exchangeRate) / WAD, underlyingDecimal);`, the `WAD` here is a constant 1e18.When the `underlyingDecimal` is 1e6 like USDT, any amount less than 1000000USDT will become 0.Here is a POC for this, add this to `test/foundry/uToken/TestMintRedeem.t.sol` and you can run it.
```solidity
function testRedeemUTokenX() public {
        vm.startPrank(ALICE);
        uToken.redeem(100 * 1e6, 0); //@audit
    }
```
change `tokenDecimals` in `test/foundry/TestWrapper.sol` to 6 and add some log function in `Utoken`::`redeem` then you can see the results:
```
  --> test/foundry/uToken/TestMintRedeem.t.sol:60:32:
   |
60 |     function testRedeemUTokenX(uint256 mintAmount) public {
   |                                ^^^^^^^^^^^^^^^^^^

proptest: Aborting shrinking after the PROPTEST_MAX_SHRINK_ITERS environment variable or ProptestConfig.max_shrink_iters iterations (set 0 to a large(r) value to shrink more; current configuration: 0 iterations)

Ran 1 test for test/foundry/uToken/TestMintRedeem.t.sol:TestMintRedeem
[FAIL. Reason: WithdrawFailed(); counterexample: calldata=0x4758717a0000000000000000000000000000000000000000000000000000000000367ca1 args=[3570849 [3.57e6]]] testRedeemUTokenX(uint256) (runs: 0, μ: 0, ~: 0)
Logs:
  underlyingAmount before decimalReducing:  100000000
  underlyingAmount after decimalReducing:  0
```
You can see that after `decimalReducing()` the amount become 0.
The way to solve it is to change `WAD` to 1e6, since it is a constant  and from the comment and code style the dev seems doesn't realize it is a problem, so the constant **is very likely to be left unchanged during deployment.**

**Comment by crypt0nX** [comment]
Escalate
test

**Comment by sherlock-admin3** [comment]
> Escalate
> test

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
