### ISSUE TITLE
Bigsam - Missing accrueInterest() Update Lead to inaccurate New Borrow index calculation

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-union-finance-update-2-judging#30]
Bigsam

Medium

# Missing accrueInterest() Update Lead to inaccurate New Borrow index calculation

## Summary
Borrow Index are not updated before the Borrow rate is changed by admin leading to inconsistencies in accrued rewards.

## Vulnerability Detail

The vulnerability arises from the lack of accrual of interest before changing the interest rate model in the `setInterestRateModel` function. In its current implementation, the function directly sets the new interest rate model without updating the borrow index, leading to inconsistencies in accrued rewards. 

Here is the current implementation of the function:

 ```solidity
  /**
     *  @dev Change to a different interest rate model
     *  Accept claims only from the admin
     *  @param newInterestRateModel_ New interest rate model address
     */
    function setInterestRateModel(address newInterestRateModel_) external override onlyAdmin {
        address oldInterestRateModel = address(interestRateModel);
        address newInterestRateModel = newInterestRateModel_;
        interestRateModel = IInterestRateModel(newInterestRateModel);
        emit LogNewMarketInterestRateModel(oldInterestRateModel, newInterestRateModel);
    }
```

## Impact

When the interest rate model is changed without updating the borrow index, the accrued interest is not properly accounted for. This can result in users either losing their accrued interest or being charged more than they should be, depending on whether the new interest rate is lower or higher than the old rate leading to Inconsistency in Borrow index because of the change in borrowrate of the entire protocol.

This issue has been identified in previous audits as well:

1. [Munchables Findings Issue #20](https://github.com/code-423n4/2024-05-munchables-findings/issues/20)
2. [Revert Lend Findings Issue #400](https://github.com/code-423n4/2024-03-revert-lend-findings/issues/400)

These references highlight the importance of updating indices before making changes to interest rates or other critical parameters to ensure accurate and fair interest calculations.

## Code Snippet

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L377-L386

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L525-L530

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L771-L772

## Tool used

Manual Review

## Recommendation

Update Borrow index before changing the borrow Rate

```solidity

  function setInterestRateModel(address newInterestRateModel_) external override onlyAdmin {

        address oldInterestRateModel = address(interestRateModel);

++   if (!accrueInterest()) revert AccrueInterestFailed();

        address newInterestRateModel = newInterestRateModel_;
        interestRateModel = IInterestRateModel(newInterestRateModel);
        emit LogNewMarketInterestRateModel(oldInterestRateModel, newInterestRateModel);
    }

```

**Comment by Tomiwasa0** [comment]
Thanks for judging @mystery0x, I believe this is a valid medium. Updating InterestRateModel is not an admin mistake it is the normal implementation.
 Compound finance has the same implementation but it was properly handled and interest was collect before updating the interest rate.
https://github.com/compound-finance/compound-protocol/blob/a3214f67b73310d547e00fc578e8355911c9d376/contracts/CToken.sol#L1075-L1084

Also issues like this have been validated as a medium recently.

https://github.com/code-423n4/2024-05-munchables-findings/issues/20

**Comment by trachevgeorgi** [comment]
Escalate
On behalf of @Tomiwasa0

**Comment by sherlock-admin3** [comment]
> Escalate
> On behalf of @Tomiwasa0 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
It's not an optimized design, nevertheless, the admin should be able to prevent this mishap considering [`accrueInterest()`](https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/market/UToken.sol#L771) is readily callable prior to calling `setInterestRateModel()`.

**Comment by Tomiwasa0** [comment]
It's an optimized design implemented by all other protocols, inaccurate borrow rate is a big impact on the borrower. Because it will not accurately reflect the actual rate as at the block.timestamp these changes will be made.

It's the only optimized way to call, 
>>  * @notice accrues interest and updates the interest rate model 
>>     * @dev Admin function to accrue interest and update the interest rate model
>>     * @param newInterestRateModel the new interest rate model to use
     *

Over the last 4months i have seen this validated in about 4-5 contracts.

https://solodit.xyz/issues/m10-updating-storage-variables-could-soft-brick-the-protocol-openzeppelin-empty-set-v2-audit-markdown

https://solodit.xyz/issues/m-04-amount-distributed-can-be-inaccurate-when-updating-weights-code4rena-backd-backd-tokenomics-contest-git

A quick search on Solodit for "updating" brought over 1000 reports like this. picked and posted just two here. Thanks for the hard work so far.

**Comment by lanrebayode** [comment]
Calling accureinterst before setting doesn't solve this issue as the bock.timestamp of both calls are different, which is the root of this issue. integrating this into the set setInterestRateModel() as done by compound is the only way to accurately set the interest rate.  This is also implemented in other functions so i see no reason why it should not be implemented correctly here.

**Comment by WangSecurity** [comment]
This issue should be invalid based on the following:
> Admin functions are assumed to be used properly, unless a list of requirements is listed and it's incomplete or if there is no scenario where a permissioned funtion can be used properly
Admin could have an incorrect call order. Example: If an Admin forgets to setWithdrawAddress() before calling withdrawAll() This is not a valid issue.
An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by Tomiwasa0** [comment]
Thank you @WangSecurity  sir Wang,

Apologies for adding more comments,
This is not a call order issue. 
The update should be done at the point of changing. @block.timestamp.

Based on the doc also there is an exception and this falls under the exception.

>>Note: if the attack path is possible with any possible value, it will be a valid issue.

>>Exception: It will be a valid issue if the attack path is based on a value currently live on the network to which the protocol will be deployed.

**Comment by WangSecurity** [comment]
To clarify what you have quoted, I didn't quote the rule about admins which has the Note and Exception you quoted, so it's not applicable here. I quoted the last line of "Direct Protocol Owner/Admin rug pulls" in the section Sherlock's Standards and the rule "Admin Input/call validation" in the section "List of Issue categories that are not considered valid". Excuse me for the confusion.

But, what would be the loss if the admin called `accrueInterest` in a couple of blocks before setting the new interest model?

**Comment by Tomiwasa0** [comment]
Thank you @WangSecurity Sir Wang,

   function accrueInterest() public override returns (bool) {
  
>>      uint256 borrowRate = borrowRatePerSecond();

        uint256 currentTimestamp = getTimestamp();
        uint256 timeDelta = currentTimestamp - accrualTimestamp;

        uint256 simpleInterestFactor = borrowRate * timeDelta;
        uint256 borrowIndexNew = (simpleInterestFactor * borrowIndex) / WAD + borrowIndex;

        accrualTimestamp = currentTimestamp;
        borrowIndex = borrowIndexNew;

        return true;
    }
uint256 borrowRate is updated based on the new value which is used for getting the new borrow index. uint256 borrowIndexNew. 

Not updating at the point of change means the next interest accrued within that block.timestamp will be calculated against the wrong borrow rate which may either inflate those fees for the passed time or deflate it. 

blocktime= 12
funds 1000000
borrow rate = 0.3%
borrowindex =1.05e18

updated 
even if done some seconds late
new borrow rate=0.5%
  uint256 simpleInterestFactor = should use formal borrowRate

borrowRate * timeDelta = 0.3%*1=0.003

but instead  we will use 

borrowRate * timeDelta = 0.5%*1=0.005


Correct rate 
 uint256 borrowIndexNew = (0.003 * 1.05e18) / 1e18 + 1.05= 1.05315.

Wrong rate 
 uint256 borrowIndexNew = (0.005 * 1.05e18) / 1e18 + 1.05= 1.05525.

Calling this late inflates the borrow index hence user pays more

funds borrowed  1000000
 
real rate = 1000000 * 1.05315 = 1,053,150

Wrong rate = 1000000 * 1.05525 = 1,055,250

difference = 1,055,250 - 1,053,150 = $2,100 

Users pays $2100 extra because of this error based on this example.

**Comment by WangSecurity** [comment]
Hm, but isn't borrow rate of 0.3% per second is too much? If accruing 0.3% per second, in 330 second you'll accrue 99% if my math is correct. But even with such inflated borrow rate, the loss is 0.19% and I believe with normal borrow rate it would be much lower. Additionally, I believe counting a larger borrow rate for a couple of more blocks is not a reasonable loss. Moreover, the admin can bundle those transactions in the same block. 

Hence, taking all the arguments above altogether, I believe it's low severity. Planning to reject the escalation and leave the issue as it is.

**Comment by Tomiwasa0** [comment]
@WangSecurity ,

All recommendations given are an alternative fix to this issue. These are assumptions of how admin can call this. The impact validity is not an issue again.  

>Additionally, I believe counting a larger borrow rate for a couple of more blocks is not a reasonable loss.

Because of the potential loss it should be a medium. 

BASED ON THE RULES 

 How to identify a medium issue:
Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.

Breaks core contract functionality, rendering the contract useless or leading to loss of funds.

**Comment by Tomiwasa0** [comment]
IF THIS FUNCTION IS BUNDLED TOGETHER, this is clearly a fix to this issue. Calling this function "as it is" leads to inflated Borrow index!!! There is a clear flow bug in the function. It is simpler to fix the issue than to   "BUNDLED TOGETHER"!

Fixing the logic is the permanent solution here. 

As a matter of reference, #122 and #133 issues have a lower impact when compared to this!

**Comment by WangSecurity** [comment]
> IF THIS FUNCTION IS BUNDLED TOGETHER, this is clearly a fix to this issue. Calling this function "as it is" leads to inflated Borrow index!!! There is a clear flow bug in the function. It is simpler to fix the issue than to "BUNDLED TOGETHER"!

As you can see, calling functions in bundle is not a sole argument, and was the last one I mentioned. Moreover, the current codebase implementation allows for it.

As I've said, the loss with a significantly inflated borrow rate for a couple of blocks is less than 0.1% and I believe with a normal and appropriate borrow rate the loss will be insignificant. That is why I believe that this issue is low severity.

Regarding the other 2 issues you mentioned, I disagree that their impact is lower. And let's not use other issues as examples.

Hence, the decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by Tomiwasa0** [comment]
1. There is no multicall function or am i missing something?  i don't see how these transactions will be batched.
2. 0.1% Of  1 million is $1000. dust amounts are usually 100 wei or less. if indeed $1000 is considered dust amount.
3. >  I believe with a normal and appropriate borrow rate the loss will be insignificant. That is why I believe that this issue is low severity. 
 we can't always assume that all will go well, even if all those goes well an impact is still present

@WangSecurity, possibly laid out my last agrument sir wang, hopefully you considered all evidence.

**Comment by maxweng** [comment]
Our thinking here is to avoid circular dependency, ie. to have `UToken.sol` to import `InterestRateModel` only. So when swapping the interest rate model, the proposal will have to update the interest, then swap the model.

**Comment by Tomiwasa0** [comment]
Amount are scaled making this impact a solid one
>Our thinking here is to avoid circular dependency

 I believe there The report highlights the flaw in the implementation. The protocol can actually handle this with alternative means.

Thanks for the input sir Alex, I believe we are all here for the safety of the protocol and if the decision taken here to implement or not to implement (the stated issue still persists) will lead to the safety of both users and the protocol I believe it is ok. Thanks a lot for all your inputs Sir wang and Sir Max. Wish the protocol the very best. Thank you.

**Comment by WangSecurity** [comment]
> There is no multicall function or am i missing something? i don't see how these transactions will be batched

As I understand multicall function is not the only way to call two functions in a batch, you can also do this via smart contract or smart wallet. Please note, it's the least important argument I have.

> 0.1% Of 1 million is $1000. dust amounts are usually 100 wei or less. if indeed $1000 is considered dust amount.

The problem with numbers is that they're relative. For example, $10 is only 0.001% out of 1 million, but at the same time it's 10% out of $100. Hence, I prefer to use percentages and not amounts of tokens, so we can get a less subjective picture on the loss.

Hence, my decision remains the same and this issue is low severity. Planning to reject the escalation and leave the issue as it is.

**Comment by Tomiwasa0** [comment]
We should look at this objectively and not subjectively a LOSS is a LOSS in respective of the percentage. 

It is the value that matters. 
A LOSS is never calculate as Percentage in an financial sector.

Kindly check Max's recently comment.
 The total borrowed amount in the protocol can go as high s over 10 million, not subjected to just a figure.

 The impact is clear but According to your statement

> The problem with numbers is that they're relative. For example, $10 is only 0.001% out of 1 million, but at the same time it's 10% out of $100. Hence, I prefer to use percentages and not amounts of tokens, so we can get a less subjective picture on the loss.
Hence, my decision remains the same 

If a loss can be avoided regardless of the percentage? Why not avoid It.

**Comment by Tomiwasa0** [comment]
Judging should be guided by the rules and the rules are clear on what a medium is. i sincerely hope that the rule is followed here.
 

DOcs. 
> How to identify a medium issue:
Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.

**Comment by WangSecurity** [comment]
> We should look at this objectively and not subjectively a LOSS is a LOSS in respective of the percentage.
Judging should be guided by the rules and the rules are clear on what a medium is. i sincerely hope that the rule is followed here.

Judging is based on the rules and as you can clearly see not every loss is considered and issue, i.e. `losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.` and I believe the loss here doesn't exceed it.

> It is the value that matters.
A LOSS is never calculate as Percentage in an financial sector.

As I've said, the loss calculated as the amount is subjective and doesn't address the significance of the loss. As I've showed in the previous example, the loss of $10 is significant for one user and is dust for another, that's why percentage is used.

> Kindly check Max's recently comment.
The total borrowed amount in the protocol can go as high s over 10 million, not subjected to just a figure

I've checked his comment, and as we can see he says the proposal will first update the interest and then the model will be switched, which is what leads to loss being insignificant.

> If a loss can be avoided regardless of the percentage? Why not avoid It

By avoiding the loss you mean fixing the issue? Sponsor can decide which issue to fix regardless of it being valid H/M. And we have to validate the issue not based on the fact that it can be fixed and will improve the protocol. Again, as I've said and you correctly quoted, not every loss is medium severity.

Hence, the decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by Tomiwasa0** [comment]
>Judging is based on the rules and as you can clearly see not every loss is considered and issue, i.e. losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss. and I believe the loss here doesn't exceed it.

The loss here affects all borrowers and not just one. The loss exceeds small affecting all borrowers evenly and believing it is small is an assumption is an error. Assumptions should not be the base for the final judgement here but facts .

**Comment by WangSecurity** [comment]
The loss is small based on the calculations you provided above, not because I just think it is. And this loss doesn’t exceed small and finite amounts. The decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by Tomiwasa0** [comment]
In many contexts, dust amounts are those that are less than $1 USD.
In some cases, especially in competitive settings like audit contests, dust might be defined as even lower amounts, such as less than $0.10 or $0.01 USD.
The loss i described is far from being a dust amount. Unless the definition of dust amount is 10,20,200,2000

**Comment by WangSecurity** [comment]
I’ve already said, explained and gave an example why using a number is subjective to understand if the loss is small or not. That’s why we use a percentage. With an extreme borrow rate the loss is only 0.19%, with a normal borrow rate it will be even less than 0.01%, that’s why I believe this issue is low severity. 

I’m sorry, but it’s not a debatable question and if there’s no other information that wasn’t considered, the decision remains the same, reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [trachevgeorgi](https://github.com/sherlock-audit/2024-06-union-finance-update-2-judging/issues/30/#issuecomment-2241270011): rejected
