### ISSUE TITLE
Bigsam - Current Implementation of deposit in Assetmanager.sol fails to iletarate to fill floor in the moneymarket and instead deposits all into one moneymarket

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-union-finance-update-2-judging#98]
Bigsam

Medium

# Current Implementation of deposit in Assetmanager.sol fails to iletarate to fill floor in the moneymarket and instead deposits all into one moneymarket

## Summary

The current implementation of the `deposit` function in `AssetManager.sol` does not properly distribute funds among money markets according to their floors and ceilings. This can result in all funds being deposited into a single money market, potentially bypassing the ceiling limits.

## Vulnerability Detail
https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/asset/AssetManager.sol#L307

The `deposit` function is intended to first fill the floors of supported money markets before distributing the remaining funds to the ceilings. However, the current implementation does not correctly iterate through the money markets to fill the floors, leading to all funds being deposited into a single money market. This could allow users to bypass the ceiling limits if they deposit a large amount of funds.

Here is the current implementation of the function:

```solidity
function deposit(
    address token,
    uint256 amount
) external override whenNotPaused onlyAuth(token) nonReentrant returns (bool) {
    IERC20Upgradeable poolToken = IERC20Upgradeable(token);
    if (amount == 0) revert AmountZero();

    if (!_isUToken(msg.sender, token)) {
        balances[msg.sender][token] += amount;
        totalPrincipal[token] += amount;
    }

    bool remaining = true;
    poolToken.safeTransferFrom(msg.sender, address(this), amount);
    if (isMarketSupported(token)) {
        uint256 moneyMarketsLength = moneyMarkets.length;
        for (uint256 i = 0; i < moneyMarketsLength && remaining; i++) {
            IMoneyMarketAdapter moneyMarket = moneyMarkets[i];
            if (!moneyMarket.supportsToken(token)) continue;
        @audit >> checks if floor has been reached >>>    if (moneyMarket.floorMap(token) <= moneyMarket.getSupply(token)) continue;
        @audit >> deposits all into one money market, risk that can allow for floor + amount>ceiling  >>>    poolToken.safeTransfer(address(moneyMarket), amount);
            if (moneyMarket.deposit(token)) {
                remaining = false;
            }
       ...................................................................
  
}
```

## Impact

The incorrect handling of the floors can lead to a single money market receiving more funds than its ceiling limit, resulting in potential overexposure and liquidity issues. This can negatively impact the stability and performance of the protocol. This is not submitted as a high because the admin can rebalance this but it should be implemented appropriately.

## Code Snippet

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/asset/AssetManager.sol#L291-L292

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/asset/AssetManager.sol#L293-L303

https://github.com/sherlock-audit/2024-06-union-finance-update-2/blob/main/union-v2-contracts/contracts/asset/AssetManager.sol#L268-L326

## Tool used

Manual Review

## Recommendation

Update the `deposit` function to correctly iterate through the money markets, ensuring that floors are filled before distributing the remaining funds to the ceilings. The function should check the amount needed to fill each money market to the floor before attempting to fill to the ceiling. Here is the updated code:

```solidity
function deposit(
    address token,
    uint256 amount
) external override whenNotPaused onlyAuth(token) nonReentrant returns (bool) {
    IERC20Upgradeable poolToken = IERC20Upgradeable(token);
    if (amount == 0) revert AmountZero();

    if (!_isUToken(msg.sender, token)) {
        balances[msg.sender][token] += amount;
        totalPrincipal[token] += amount;
    }

    poolToken.safeTransferFrom(msg.sender, address(this), amount);

    if (isMarketSupported(token)) {
        uint256 moneyMarketsLength = moneyMarkets.length;

        // Iterate markets to fill floors
        for (uint256 i = 0; i < moneyMarketsLength && amount > 0; i++) {
            IMoneyMarketAdapter moneyMarket = moneyMarkets[i];

            if (!moneyMarket.supportsToken(token)) continue;

            uint256 currentSupply = moneyMarket.getSupply(token);
            uint256 floor = moneyMarket.floorMap(token);
            if (currentSupply >= floor) continue;

   ++         uint256 amountToDeposit = floor - currentSupply;
   ++        if (amountToDeposit > amount) {
   ++            amountToDeposit = amount;
            }

   ++        poolToken.safeTransfer(address(moneyMarket), amountToDeposit);
            if (moneyMarket.deposit(token)) {
     ++           amount -= amountToDeposit;
    ++   if (amount==0){
         remaining = false;
            }
        }

 
}
```

**Comment by twicek** [comment]
Escalate
This is not an issue, this is as designed. Money markets can be filled until their floor value is reached. Then, if all floors are filled, any amount can be sent to a money market until the ceiling is exceeded. Going pass the ceiling is not an issue. Therefore exceeding the ceiling when iterating to fill the floors is still not an issue as well. If the ceiling is reached the money market will just be skipped, which will not have any impact.

**Comment by sherlock-admin3** [comment]
> Escalate
> This is not an issue, this is as designed. Money markets can be filled until their floor value is reached. Then, if all floors are filled, any amount can be sent to a money market until the ceiling is exceeded. Going pass the ceiling is not an issue. Therefore exceeding the ceiling when iterating to fill the floors is still not an issue as well. If the ceiling is reached the money market will just be skipped, which will not have any impact.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by lanrebayode** [comment]
Thanks for the input twicek,

 1. money market should be filled until their floor is filled but the current implementation can go above, By depositing all the funds available into the system instead of filling the floor first with a risk of breaking an invariant set in the money-market (ceiling).  
 Kindly read me comment in the protocol's implementation


```solidity
if (isMarketSupported(token)) {
    uint256 moneyMarketsLength = moneyMarkets.length;
>>      // assumption: markets are arranged in order of decreasing liquidity
>>we want to fill floor not go above>>    // iterate markets till floors are filled
>>      // floors define minimum amount to maintain confidence in liquidity
    for (uint256 i = 0; i < moneyMarketsLength && remaining; i++) {
        IMoneyMarketAdapter moneyMarket = moneyMarkets[i];

        if (!moneyMarket.supportsToken(token)) continue;
        if (moneyMarket.floorMap(token) <= moneyMarket.getSupply(token)) continue;

        poolToken.safeTransfer(address(moneyMarket), amount);
        if (moneyMarket.deposit(token)) {
            remaining = false;
        }
    }
}
```
we are to fill floors first. 
 2. Going past the ceiling is an issue, It breaks an invariant set in the money-market. Breaking an invariant in a contract is generally considered a significant issue. Invariants are conditions that must always hold true for an object to be in a valid state. When an invariant is broken, it indicates that the object is in an invalid state. 
 
 Kindly read me comment in the protocol's implementation in the moneymarket.
 ```solidity
  /**
>>    * @dev Set the ceiling balance for this token.
>>     * @dev The ceiling is the max balance we want to be managed by this adapter
     * @param tokenAddress The Token address
     * @param ceiling Ceiling balance
     */
    function setCeiling(address tokenAddress, uint256 ceiling) external onlyAdmin {
        ceilingMap[tokenAddress] = ceiling;
    }
```

Therefore, it’s prudent to treat breaking an invariant as at least a medium issue to ensure the integrity and reliability of the system. 

A medium according to Sherlock rule- >>Breaks core contract functionality, rendering the contract useless or leading to loss of funds. 

Going above the ceiling renders the ceiling check below useless. hence a valid medium(invariant must hold always).

```solidity
   uint256 supply = moneyMarket.getSupply(token);
                uint256 ceiling = moneyMarket.ceilingMap(token);
>>If we are not concerned about the ceiling this check becomes useless>>    if (supply + amount > ceiling) continue;

```

Kindly read the following reports that addresses breaking invariants in past Sherlock contests-

https://solodit.xyz/issues/m-13-targetthreshold-can-be-set-below-minthreshold-violating-important-invariant-sherlock-hats-hats-git

https://solodit.xyz/issues/h-1-signers-can-bypass-checks-and-change-threshold-within-a-transaction-sherlock-hats-hats-git

https://solodit.xyz/issues/m02-bypass-contract-invariants-openzeppelin-set-protocol-audit-markdown

There are over 20 examples of this but i believe this should be enough reference.

**Comment by mystery0x** [comment]
lanrebayode delineates very good points. Will have to ask sponsors reasonings for disputing this finding.

**Comment by twicek** [comment]
You just need to look at this line to know that the ceiling is meant to be exceeded:
```solidity
                if (supply + amount > ceiling) continue;
```
The money market is skipped if the ceiling is exceeded. Going pass the ceiling doesn't break any invariants it's meant to happen.
@lanrebayode @mystery0x

**Comment by Tomiwasa0** [comment]
if (supply + amount > ceiling) continue;  
This means the ceiling is being protected the protocol wants to believe iteration was done correctly when floor was filled and next protect the ceiling. And already we know their present implementation does not fully protect against that during the first iteration, hence it is an issue to go above during the first iteration since we will never be able to ideally.

How invariants works
1. Invariant 1+1 must be =2 
2. first iteration can allow 1+1 go above 2 let's say 3.
3. second iteration that should enforce 2 is unable to maintain the contract state at 2.
4. hence 1+1 is not 2 again. invariant broken == bug.

**Comment by WangSecurity** [comment]
Firstly, historical decisions (especially, on other platforms/firms) are not a source of truth. 

Secondly, just breaking an invariant doesn't make an issue medium per se.

Thirdly, as I understand it works as it should. I don't think the comment says that we should fill exactly the floor initially, i.e. if the floor is 100 tokens and we deposit 107 tokens, I don't see any issue and it also means the floor is filled. About the ceiling, I believe it's also the design to allow the first deposit that would pass the ceiling to go through and not allow the next ones.
Moreover, I don't see any impact in protocol working this way. Hence, even if it's an invariant and it's not held correctly, I don't see any medium impact here.

Planning to accept the escalation and invalidate the report.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [twicek](https://github.com/sherlock-audit/2024-06-union-finance-update-2-judging/issues/98/#issuecomment-2240803436): accepted
